spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/eblog
    username: username
    password: password
  redis:
    host: host
    port: 6379
  data:
    elasticsearch:
      cluster-name: cluster-name
      cluster-nodes: cluster-nodes
      repositories:
        enabled: true
  rabbitmq:
    username: username
    password: password
    host: host
    port: 5672
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
file:
  upload:
    dir: ${user.dir}/upload